
INSERT INTO users (
    name, email, password) 
    VALUES (
    'Wayne Singleton', 'keiraestes@icloud.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
    INSERT INTO users (
    name, email, password) 
    VALUES (
    'Ethel Ingram', 'tristanwells@google.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
    INSERT INTO users (
    name, email, password) 
    VALUES (
    'Luke Hodges', 'cadencemcdowell@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
    INSERT INTO users (
    name, email, password) 
    VALUES (
    'Beatrice Johnson', 'cameronsparks@mail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
    
INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
    VALUES (
    'Return diagram', 'Discovery stay kitchen younger warn strip yard ground journey knowledge effort related rhyme sure thank face scale our longer body sometime yet army classroom refused ring want earlier swept day some husband root sum hall reader announced within coffee been power smell basis fighting card magnet prevent shorter whom breakfast combine contrast dream sad leather national unknown none scene personal push automobile very additional allow setting school social allow hang human honor wait breathing plus dirt plastic bottle require deal behind manner lower valuable interior bad ground strip rough rather frequently struck can map beauty next happened kept youth wood would chest stay known rate basic fort court entire lie height race work wave fish since flame ring stage per ask every run down cap southern newspaper paper realize thirty hill time desk whom selection brush needed neighbor avoid cut busy paper won dish shoulder bill mouse tree passage begun rush surrounded evidence vapor exciting shut bound whispered band century method little go brave zipper opinion boy hot mental mission shaking road solar cave remain curious exchange closer few because frighten plenty same dinner route coming ring meant contrast visit simplest law everything blanket willing political impossible toward cook giant piano fruit oldest railroad any identity wing hair develop nearby thirty flow separate feathers writing copy parent adult doing him passage exact animal worse wash any instrument press twelve slipped great stared beauty hope early tongue pressure tales running clothes news heard lake grow against plus primitive paragraph themselves tie after enjoy cut dawn bone clearly dig vessels began each also president still married slipped skill review second pocket image pocket glass made harder alphabet limited dinner camp pan frame chart slowly mathematics combine slip add did mad hit library stuck outside produce sentence getting thousand research building composed window', 448, 'https://images.pexels.com/photos/783682/pexels-photo-783682.jpeg', 'https://images.pexels.com/photos/783682/pexels-photo-783682.jpeg?auto=compress&cs=tinysrgb&h=350', 95187, 6, 9, 6, true, 'Yukon', 'Whitehorse', 'Canada', '745 Fovcid Turnpike', '78074');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
    VALUES (
    'Town recognize', 'Separate advice child any rest stream evidence measure log large nine replace test income member breathe everything wagon strong together identity judge gray block student bat vapor cast tank shake do thy scientist earlier beautiful radio radio since taught farm sail scale slabs slept remain farm else crop branch stove magic leave production no growth nearby crack combine author private ordinary action suggest flower caught motor depend lesson discovery rest hope population entire plate bring lungs floor cause orange pen your equipment decide particularly row liquid pool gray fifty tried powder flew beautiful sheet base deal pie paragraph deal alike strong share effect tail know instrument double outer touch perfect anywhere package like shorter market mud particularly fourth teacher trace husband cake tent soldier fight remember noun hollow meet move either range earth dot bus eight wood grabbed bar part practical idea stone dust human seldom rather beat mine path thought in gasoline stage sentence break rising brown shop aid tail led happily attention noon jack toy indicate idea came medicine heavy jar half distance zoo widely temperature whether brief oxygen stone additional degree wait teeth salt surface differ present call doing poor particularly fastened magnet apartment consider forward concerned manufacturing visit needle bound unknown inside shallow situation shot cutting balance glass grandmother team fierce well income couple angle changing us blue thou yourself me her it would gone cake source but supply buffalo orbit oxygen select capital so easy source forty sky out army guess ring man air plane feathers electric test danger has direct film mind ask must using ball pound make driven him alone shadow search unit entire golden fourth movement leg roar heading division brave heavy division water unless run jack characteristic sent according complete throat speech triangle explanation only sugar science himself before done fire', 602, 'https://images.pexels.com/photos/2079626/pexels-photo-2079626.jpeg', 'https://images.pexels.com/photos/2079626/pexels-photo-2079626.jpeg?auto=compress&cs=tinysrgb&h=350', 45130, 1, 1, 0, true, 'Prince Edward Island', 'Alberton', 'Canada', '1751 Mafmic Parkway', '67345');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
    VALUES (
    'Like arrow', 'Ahead sit stairs loud sick different per to who compound phrase language directly wherever ill fifty low new satellites famous begun merely rod goose probably tune slowly instead sheep grown lesson gravity hold accident letter peace thin spoken behavior lower atomic hide situation ten during ancient visitor came shot live wooden fell send slightly form familiar construction date army sharp me article exclaimed faster having feature involved provide else chose owner hope quick having doing production sum joined during worse winter fire prepare deer indeed between customs wonderful hit not world subject night fence west successful someone quietly honor education college myself slight highway riding oldest anybody stay becoming daily surprise people taste stone saddle island disappear truck food goes hot force law exciting blank meal author cut thank value saw atomic meal gave still flies electric pan leg blind square thy burst toward trouble chemical represent sink lack composition try vegetable stay floor any note measure plus except arrangement loud frozen path congress shaking type call hospital love nation start cry practice riding my natural paragraph bread directly government within tube silver ball mission else substance watch being thousand somewhere live egg worry support higher doing tent bit car any enough weak shop century idea living skill explain task whenever task be cotton crop herd safety salt guard afternoon greater door factor recently sign sand beyond level failed teeth height gravity reach service nose stove officer fox compound did active will vegetable experience hunt distant having faster author spirit owner gas built explain work middle them soft personal pony consist slowly table huge plate adventure cattle unless rocky chief lot riding forth silence later wave brought pitch too news building zebra different lesson sit straw egg leaf member mathematics sentence brain close sit being organization influence carbon model frame', 857, 'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg', 'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&h=350', 92451, 8, 7, 3, true, 'Northwest Territories', 'Town of Hay River', 'Canada', '1096 Womew Street', '74370');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
    VALUES (
    'White equipment', 'Hearing old story problem cost melted fox are log reason actual wife model top art stay needle within tea pilot track quietly pain probably myself make remove rest higher balance train break property basic teeth empty brave soft frequently perfect divide fire dear favorite married noun local properly perhaps fire you weak sentence dawn suppose hundred on hundred plural planning poem land hand believed leaf ordinary just avoid review parent enjoy that voyage follow begun engine somewhere whenever result soft riding massage swing paragraph well avoid daily wooden flag slabs lose end dangerous friendly gas student desert visit making tail compound health crack fifty her factor shirt stranger finish wide please said clean shinning tears wool each religious another trap independent sand ship monkey put ill poetry interior tube ruler avoid circle tape mission refer wear lovely basket pole single gather kept driven use memory stretch land sum feed mass by lion salmon certainly reader feed his mail way leather ship sat medicine mud leaf port oxygen smallest orbit movement cannot personal meant hardly careful rest dangerous reader morning feel per sheet storm park out statement policeman power page struggle young gave ring bigger room slave origin military bit leave vegetable leave lungs fewer color four plain already dropped social earth earlier arrangement dress circle simplest hold acres herd fell throw chemical firm small blanket belt engineer easily telephone nest creature twelve unit none thin golden everybody interior active into expression something wrote feel position balance put least instead yet repeat bend east gain clothes musical increase skin form slow could carefully baseball combination moment flame around clay collect exactly animal week person central wife grass dirt refer crowd post gun something pay red exchange act escape cheese becoming gold screen active wide power social song universe meant fairly death', 826, 'https://images.pexels.com/photos/2098443/pexels-photo-2098443.jpeg', 'https://images.pexels.com/photos/2098443/pexels-photo-2098443.jpeg?auto=compress&cs=tinysrgb&h=350', 5913, 9, 1, 2, true, 'Prince Edward Island', 'Alberton', 'Canada', '1371 Davguv Plaza', '30153');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
    VALUES (
    'Happy major', 'Degree away throat sail fix colony around held nervous flow diameter mass describe brick riding hidden earth matter powder pig mountain of suit mouse rule for wooden wise effort hope account treated hall compound pile did favorite stone clock science attention station weight correctly die package somebody me near driver prevent sand mad have across outline cotton recall chamber worth plus cell these whispered easier behind type judge hundred mean pupil square boy arrive back design conversation let birds colony forty instance refer operation grade theory acres ran tongue greater gave driver indicate fire potatoes visitor rocket roar call part carbon show six rapidly recognize mission know leader saved using gravity straw warn gun suit dress porch bound leaving have length attempt volume jack were setting forgotten bottom congress sing her road process chapter island human plant weather until worth century together shoulder enjoy orange recently related medicine goes baseball ask brave widely either after smallest rough government unless lamp purple equally attention forth hay rear share common peace charge stomach ranch no carried these column donkey ourselves few war me us pattern grandmother package blood bare laid boy corn difficulty court flies another moment area consonant century mad machine wire definition appearance principal various thank about kept tube stuck animal husband play even needs wife even replied victory bigger whole post element southern gently electric muscle dozen typical doctor mill wolf aware wore won cross blew quite agree dance motion view cave roll check chapter tree judge national table traffic fast table morning soft natural tomorrow shape smaller swim stock did music nearly explanation produce particular problem worry drop doing escape dried manner having sets pictured he generally tribe dry pie stood treated slip air stairs student zulu spirit way leather alive energy percent contain down diameter strange iron', 44, 'https://images.pexels.com/photos/2079665/pexels-photo-2079665.jpeg', 'https://images.pexels.com/photos/2079665/pexels-photo-2079665.jpeg?auto=compress&cs=tinysrgb&h=350', 63797, 9, 0, 1, true, 'British Columbia', 'Fernie', 'Canada', '1558 Diibe Path', '97716');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
    VALUES (
    'Sale flew', 'Mice pick applied list balance pride track rapidly bark fireplace wooden tide tell local wool bigger pay eat breathing music essential south idea port student usually angle among rain entire daughter mental central lower oil waste dust plus guard worry noon ground hold house satellites leather pay breathe full letter best control plain taught proud around chance hundred perhaps failed rising root universe fought maybe branch cowboy whenever brick principal lose feed beat variety gather determine ordinary prize judge watch fellow corn zipper break bend breeze we shot relationship happily goes size case voyage type constantly bowl arrive tonight union continued order thick sum key especially job agree child price porch making natural section form hundred against either vast action opportunity scientific detail into given gasoline naturally every muscle atomic stand grass member eat rear goes orange cold rubber sea equipment cake ride place into tone floating done else pleasant cool eventually unusual figure yard already wool page year ancient announced medicine season apple printed floating black few thrown solve base speech torn apart him noun strength memory swam solar tall sell pupil tail tie usual drink another free fairly listen feature death sick cage hundred birth raw score struggle anywhere correct uncle signal decide examine pay smell soon stove dot be create kill announced drink port enjoy dance chapter chosen cook great all move art rapidly when beat scene allow must principal percent husband short jar carried correct market prepare equally choose battle individual may ate hour tie changing related discovery chose turn peace whenever roof whose include sweet policeman she conversation tight spin stretch date men total development unless knew swim combination anywhere push frog held divide zero get engine excited nation society seven joined upon grabbed cow depth which volume problem pupil positive young taken parts swept', 56, 'https://images.pexels.com/photos/783682/pexels-photo-783682.jpeg', 'https://images.pexels.com/photos/783682/pexels-photo-783682.jpeg?auto=compress&cs=tinysrgb&h=350', 77658, 6, 3, 9, true, 'Northwest Territories', 'Town of Hay River', 'Canada', '834 Taoli Drive', '78816');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code) 
    VALUES (
    'Solution thought', 'Lay invented one teeth circus slabs lonely tube born sold thou primitive built numeral deer straight dinner suddenly rays pretty breathing bend church higher grade pound come atomic fourth peace company law claws dinner sudden east it fourth constantly actually dangerous doubt tightly neck it dig famous extra bat egg company something both captain part nest putting obtain attack voyage snow on finish fish wait yesterday yourself orange additional page liquid stronger affect wealth inside speed lips couple sweet smile introduced common in onto deep brain other start organization hot wise height higher poor saddle generally office lower refer market stuck forty fresh above dog stomach port break itself type chief unless draw led crowd buffalo front rising necessary proud particularly interior exchange clean division elephant mountain tie post magnet nearer plain dog weight clay apartment pole soil entire part climb sunlight go leg school step term offer silence want stock understanding became serve honor better rain spread captain original sang safe figure park doll lost national simple exist certain salmon want mission hungry favorite yard stood rope gulf move shells enjoy chief rather stood today noun dot teeth declared flag tall bar sail party everywhere or heading write next forest would grain universe breakfast serious cannot consist us something heading cup loud yesterday caught beyond younger jack giant design replied selection seems mean those interest clear changing music strip rain dozen daughter planning crack whom stomach mouth ship than pound round riding explanation phrase eaten which concerned railroad serve show therefore never band hung its honor slow replied horse sister feet prepare anyway birthday baby account afternoon brown powder opposite tree involved lunch length arrive cut catch field hay kill society wife mile fast saddle supply limited if keep to our nice second chemical taught clock rush what grandfather', 669, 'https://images.pexels.com/photos/1449729/pexels-photo-1449729.jpeg', 'https://images.pexels.com/photos/1449729/pexels-photo-1449729.jpeg?auto=compress&cs=tinysrgb&h=350', 18157, 9, 6, 6, true, 'New Brunswick', 'Miramichi', 'Canada', '406 Seore Ridge', '83176');
    
INSERT INTO reservations (
    id, guest_id, property_id, start_date, end_date) 
    VALUES (
    1015914, 208, 642, '2020-01-17', '2020-01-28');
    INSERT INTO reservations (
    id, guest_id, property_id, start_date, end_date) 
    VALUES (
    1015915, 90, 292, '2016-05-12', '2016-05-29');
    INSERT INTO reservations (
    id, guest_id, property_id, start_date, end_date) 
    VALUES (
    1015916, 880, 419, '2023-02-14', '2023-02-17');
    INSERT INTO reservations (
    id, guest_id, property_id, start_date, end_date) 
    VALUES (
    1015917, 660, 528, '2022-03-12', '2022-04-04');

INSERT INTO property_reviews (
    guest_id, property_id, reservation_id, rating, message) 
    VALUES (
    198, 997, 1010769, 4, 'Li cemu pinvo isedov zo gepfa barago lalnajbe taja do molagha obukijne kizco udhod mu nojsod.');
    INSERT INTO property_reviews (
    guest_id, property_id, reservation_id, rating, message) 
    VALUES (
    85, 893, 1010048, 3, 'Avadevow taztaop pedtefuj napiju pa na kabpahu tawus molcot befweub wooduh wod jujabpu dofafa pak.');
    INSERT INTO property_reviews (
    guest_id, property_id, reservation_id, rating, message) 
    VALUES (
    200, 951, 1011048, 5, 'Pu zag pakwoc ufiusi wilzo verur laav miishum cupenofew wobe lim ganiej kizobilav umga.');
    INSERT INTO property_reviews (
    guest_id, property_id, reservation_id, rating, message) 
    VALUES (
    695, 138, 1012931, 4, 'Ze doruvfec la hoz cegave za gobutilun ada rejiz sun bolefol ti wi ef orsupa.');
